name: python_course
dependencies:
- alabaster=0.7.9=py27_0
- anaconda=4.0.0=np110py27_0
- anaconda-client=1.5.3=py27_0
- anaconda-navigator=1.2.3=py27_0
- argcomplete=1.0.0=py27_1
- astroid=1.4.8=py27_0
- astropy=1.2.1=np111py27_0
- babel=2.3.4=py27_0
- backports.functools_lru_cache=1.2.1=py27_0
- backports.shutil_get_terminal_size=1.0.0=py27_0
- backports_abc=0.4=py27_0
- basemap=1.0.8.dev0=np111py27_2
- beautifulsoup4=4.5.1=py27_0
- bitarray=0.8.1=py27_0
- blas=1.1=openblas
- blaze=0.10.1=py27_0
- bokeh=0.12.3=py27_0
- boto=2.43.0=py27_0
- boto3=1.4.1=py27_0
- botocore=1.4.67=py27_0
- bottleneck=1.2.0=np111py27_0
- cairo=1.12.18=8
- cdecimal=2.3=py27_2
- certifi=2016.9.26=py27_0
- cffi=1.8.3=py27_0
- chest=0.2.3=py27_0
- click=6.6=py27_0
- cloudpickle=0.2.1=py27_2
- clyent=1.2.2=py27_0
- colorama=0.3.7=py27_0
- conda-manager=0.4.0=py27_0
- configobj=5.0.6=py27_0
- configparser=3.5.0=py27_0
- contextlib2=0.5.3=py27_0
- cryptography=1.5.2=py27_0
- curl=7.49.1=1
- cycler=0.10.0=py27_0
- cython=0.25.1=py27_0
- cytoolz=0.8.0=py27_0
- dask=0.12.0=py27_0
- datashape=0.5.2=py27_0
- decorator=4.0.10=py27_0
- dill=0.2.5=py27_0
- distributed=1.14.1=py27_0
- docutils=0.12=py27_2
- dynd-python=0.7.2=py27_0
- entrypoints=0.2.2=py27_0
- enum34=1.1.6=py27_1
- et_xmlfile=1.0.1=py27_0
- fastcache=1.0.2=py27_1
- flask=0.11.1=py27_0
- flask-cors=3.0.2=py27_0
- fontconfig=2.11.1=3
- freetype=2.6.3=1
- funcsigs=1.0.2=py27_0
- functools32=3.2.3.2=py27_1
- futures=3.0.5=py27_0
- geos=3.4.2=2
- gettext=0.19.7=1
- gevent=1.1.2=py27_0
- glib=2.48.0=4
- greenlet=0.4.10=py27_0
- grin=1.2.1=py27_3
- h5py=2.6.0=np111py27_6
- harfbuzz=1.0.6=0
- hdf5=1.8.17=7
- heapdict=1.0.0=py27_1
- icu=56.1=4
- idna=2.1=py27_0
- imagesize=0.7.1=py27_0
- ipaddress=1.0.17=py27_0
- ipykernel=4.5.0=py27_0
- ipython=5.1.0=py27_1
- ipython_genutils=0.1.0=py27_0
- ipywidgets=5.2.2=py27_2
- isort=4.2.5=py27_0
- itsdangerous=0.24=py27_0
- jbig=2.1=0
- jdcal=1.3=py27_0
- jedi=0.9.0=py27_1
- jinja2=2.8=py27_1
- jmespath=0.9.0=py27_0
- jpeg=9b=0
- jsonschema=2.5.1=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=4.4.0=py27_0
- jupyter_console=5.0.0=py27_0
- jupyter_core=4.2.0=py27_0
- lazy-object-proxy=1.2.2=py27_0
- libdynd=0.7.2=0
- libffi=3.2.1=2
- libgfortran=3.0.0=1
- libiconv=1.14=3
- libpng=1.6.26=0
- libsodium=1.0.10=0
- libtiff=4.0.6=7
- libxml2=2.9.4=3
- libxslt=1.1.29=1
- llvmlite=0.14.0=py27_0
- locket=0.2.0=py27_1
- lxml=3.6.4=py27_0
- markupsafe=0.23=py27_2
- matplotlib=1.5.3=np111py27_2
- mccabe=0.5.0=py27_0
- mistune=0.7.3=py27_0
- mkl=11.3.3=0
- mkl-service=1.1.2=py27_2
- mpmath=0.19=py27_1
- msgpack-python=0.4.8=py27_0
- multipledispatch=0.4.9=py27_0
- nbconvert=4.2.0=py27_0
- nbformat=4.1.0=py27_0
- ncurses=5.9=9
- networkx=1.11=py27_0
- nltk=3.2.1=py27_0
- nose=1.3.7=py27_2
- notebook=4.2.3=py27_0
- numba=0.29.0=np111py27_0
- numexpr=2.6.1=np111py27_1
- numpy=1.11.2=py27_blas_openblas_200
- odo=0.5.0=py27_1
- openblas=0.2.18=6
- openpyxl=2.4.0=py27_0
- openssl=1.0.2j=0
- pandas=0.19.1=np111py27_0
- pango=1.40.1=0
- partd=0.3.6=py27_0
- patchelf=0.9=1
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- patsy=0.4.1=py27_0
- pcre=8.39=0
- pep8=1.7.0=py27_0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pillow=3.4.2=py27_0
- pip=9.0.0=py27_0
- pixman=0.32.6=0
- ply=3.9=py27_0
- prompt_toolkit=1.0.8=py27_0
- psutil=4.4.2=py27_0
- ptyprocess=0.5.1=py27_0
- py=1.4.31=py27_0
- pyasn1=0.1.9=py27_0
- pycairo=1.10.0=py27_0
- pycosat=0.6.1=py27_1
- pycparser=2.17=py27_0
- pycrypto=2.6.1=py27_4
- pycurl=7.43.0=py27_0
- pyflakes=1.3.0=py27_0
- pygments=2.1.3=py27_1
- pylint=1.6.4=py27_0
- pyopenssl=16.0.0=py27_0
- pyparsing=2.1.10=py27_0
- pyproj=1.9.5.1=py27_0
- pyqt=4.11.4=py27_4
- pyshp=1.2.10=py27_0
- pytables=3.3.0=np111py27_0
- pytest=3.0.3=py27_0
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.7=py27_0
- pyyaml=3.12=py27_0
- pyzmq=16.0.0=py27_0
- qt=4.8.7=4
- qtawesome=0.3.3=py27_0
- qtconsole=4.2.1=py27_0
- qtpy=1.1.2=py27_0
- readline=6.2=2
- redis=3.2.0=0
- redis-py=2.10.5=py27_0
- requests=2.11.1=py27_0
- rope=0.9.4=py27_1
- s3fs=0.0.7=py27_0
- s3transfer=0.1.8=py27_0
- scikit-image=0.12.3=np111py27_1
- scikit-learn=0.18=np111py27_blas_openblas_202
- scipy=0.18.1=np111py27_blas_openblas_200
- setuptools=28.0.0=py27_0
- shapely=1.5.17=np111py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_1
- snowballstemmer=1.2.1=py27_0
- sockjs-tornado=1.0.3=py27_0
- sphinx=1.4.8=py27_0
- sphinx_rtd_theme=0.1.9=py27_0
- spyder=3.0.1=py27_0
- sqlalchemy=1.1.3=py27_0
- sqlite=3.13.0=1
- ssl_match_hostname=3.5.0.1=py27_0
- statsmodels=0.6.1=np111py27_1
- sympy=1.0=py27_0
- tblib=1.3.0=py27_0
- terminado=0.6=py27_0
- tk=8.5.19=0
- toolz=0.8.0=py27_0
- tornado=4.4.2=py27_0
- traitlets=4.3.1=py27_0
- unicodecsv=0.14.1=py27_0
- util-linux=2.21=0
- wcwidth=0.1.7=py27_0
- werkzeug=0.11.11=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=1.2.6=py27_3
- wrapt=1.10.8=py27_0
- xlrd=1.0.0=py27_0
- xlsxwriter=0.9.3=py27_0
- xlwt=1.1.2=py27_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zict=0.1.0=py27_0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.4
  - backports.functools-lru-cache==1.2.1
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - dynd==0.7.3.dev1
  - et-xmlfile==1.0.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - prompt-toolkit==1.0.8
  - sphinx-rtd-theme==0.1.9
  - tables==3.3.0

